# Generated by Django 5.0.1 on 2024-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='msg',
        ),
        migrations.AddField(
            model_name='stud',
            name='Branch',
            field=models.CharField(default='computer', max_length=40),
        ),
        migrations.AddField(
            model_name='stud',
            name='Year',
            field=models.CharField(default='first year', max_length=20),
        ),
        migrations.AddField(
            model_name='stud',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='stud',
            name='roll_no',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='stud',
            name='status',
            field=models.CharField(default='present', max_length=20),
        ),
    ]
