# Generated by Django 5.0.1 on 2024-01-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_stud_msg_stud_branch_stud_year_stud_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='date',
            new_name='attendance_date',
        ),
        migrations.RenameField(
            model_name='stud',
            old_name='status',
            new_name='attendance_status',
        ),
        migrations.RenameField(
            model_name='stud',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='stud',
            old_name='Year',
            new_name='year',
        ),
    ]
